# Generated by Django 3.2.3 on 2021-05-23 18:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250, unique_for_date='data_publikacji')),
                ('tresc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('kategoria', models.CharField(max_length=255)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_publikacji', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_aktualizacji', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Roboczy'), ('published', 'opublikowany')], default='draft', max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_publikacji',),
            },
        ),
    ]
