"""
Django settings for mojanowa project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
# ta linijka daje /backups/Desktop/mojanowa
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p171d3rawv31=$6!f0g3j0q)%*%cl16$ti5q^92kr7zy7^7j60'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'blog.apps.BlogConfig',
    'ckeditor',
    'ckeditor_uploader',
    'fizyka.apps.FizykaConfig',
    'kuchnia.apps.KuchniaConfig',
    'matma.apps.MatmaConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
# CKEDITOR_UPLOAD_PATH = 'uploads/'

#CKEDITOR_BASEPATH = "/backups/Desktop/mojanowa/static/ckeditor/ckeditor/"
# dla uploadu:

CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False
# CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
# CKEDITOR_RESTRICT_BY_DATE = True
CKEDITOR_IMAGE_BACKEND = 'pillow'  # będą miniatury 75x75

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'kama',
        'toolbar': 'full',
        'extraPlugins': ','.join(
            [
                'codesnippet',
            ]),
    },
}

# CKEDITOR_CONFIGS = {
#     'default': {
#         'update': ['Image', 'Update', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak'],
#         'skin': 'moono',
#         'toolbar_Basic': [
#             ['Source', '-', 'Bold', 'Italic']
#         ],
#         'toolbar_YourCustomToolbarConfig': [
#             {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
#             {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
#             {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
#             {'name': 'forms',
#              'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
#                        'HiddenField']},
#             '/',
#             {'name': 'basicstyles',
#              'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
#             {'name': 'paragraph',
#              'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
#                        'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
#                        'Language']},
#             {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
#             {'name': 'insert',
#              'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
#             {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
#             {'name': 'colors', 'items': ['TextColor', 'BGColor']},
#             {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
#             {'name': 'yourcustomtools', 'items': [
#                 # Custom Controls
#                 'Preview',
#                 'Maximize',
#             ]},
#         ],
#         'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
#         'tabSpaces': 4,
#         'extraPlugins': ','.join(
#             [
#                 # your extra plugins here
#                 'div',
#                 'codesnippet',
#                 'autolink',
#                 'autoembed',
#                 'embedsemantic',
#                 'autogrow',
#                 # 'devtools',
#                 'widget',
#                 'lineutils',
#                 'clipboard',
#                 'dialog',
#                 'dialogui',
#                 'elementspath'
#             ]),
#     }
# }


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'mojanowa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mojanowa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mojanowa',
        'USER': 'root',
        'PASSWORD': '19571025',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'", },


    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = False  # inaczej nie działa wyświetlane treści posta

ENV_PATH = os.path.abspath(os.path.dirname(__file__))

# STATICFILES_DIRS = os.path.join(BASE_DIR, 'static'),
STATICFILES_DIRS = [
    "/home/joe/Pulpit/mojanowa/static"
]
STATIC_URL = '/static/'
# 'http://static.jpal.ayz.pl/' - oddzielna domena.
# ------------------------------------------------
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # NIEPOTRZEBNE NA SERWERZE DEVELOPERSKIM
# STATIC_ROOT = ("/home/jpal/public_html/static/",
# ---------------------------------------------------
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')
# '/home/jpal/public_html/static/media/'
# -----------------------------------------------------
MEDIA_URL = '/media/'
# 'http://static.jpal.ayz.pl/media/' - oddzielna poddomena w home/jpal/domains

CKEDITOR_UPLOAD_PATH = 'uploads/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
print("BASE_DIR = ", BASE_DIR)
# print("STATICFILES_DIRS = ", STATICFILES_DIRS)
print("ENV_PATH = ", ENV_PATH)
print("STATIC_URL = ", STATIC_URL)
# print("STATIC_ROOT = ", STATIC_ROOT)
print("MEDIA_ROOT = ", MEDIA_ROOT)
print("MEDIA_URL = ", MEDIA_URL)
print("CKEDITOR_UPLOAD_PATH = ", CKEDITOR_UPLOAD_PATH)
